# Plugin Metadata:
# Name: __PLUGIN_KEBAB_CASE_NAME__
# Version: __PLUGIN_VERSION__
# Description: __PLUGIN_DESCRIPTION__
# Author: __PLUGIN_AUTHOR_NAME__ <__PLUGIN_AUTHOR_EMAIL__>
# 
# --- Start of Custom Configuration Template ---
# MedExpert: Custom Configuration Template
#
# This file serves as a template for creating new custom configurations from this plugin.
# Use placeholders like __COMPONENT_KEBAB_CASE_NAME__, __COMPONENT_PASCAL_CASE_NAME__,
# and __COMPONENT_UPPER_SNAKE_CASE_NAME__ where the specific component name should be inserted.

# To use the `shared_config.yaml` file, uncomment the following line and remove the `shared_config` section below.
# !include ../shared_config.yaml

shared_config:
  - broker_connection: &broker_connection
      dev_mode: ${MEDEXPERT_DEV_MODE, false}
      broker_url: ${MEDEXPERT_BROKER_URL, ws://localhost:8008}
      broker_username: ${MEDEXPERT_BROKER_USERNAME, default}
      broker_password: ${MEDEXPERT_BROKER_PASSWORD, default}
      broker_vpn: ${MEDEXPERT_BROKER_VPN, default}
      temporary_queue: ${USE_TEMPORARY_QUEUES, true}


__PLUGIN_SNAKE_CASE_NAME__: {}